using System;
using System.Collections.Generic;
using NoticeBoardV3.Models;

namespace NoticeBoardV3.DAL
{
    public class NoticeboardInitializer : System.Data.Entity.DropCreateDatabaseIfModelChanges<NoticeboardContext>
    {
        protected override void Seed(NoticeboardContext context)
        {
            var roles = new List<Role>
            {
                new Role { Role_ID=1,RoleName="Member" },
                new Role { Role_ID=2,RoleName="Owner" },
                new Role { Role_ID=3,RoleName="Admin" }
            };

            roles.ForEach(r => context.Roles.Add(r));
            context.SaveChanges();

            var statuses = new List<Status>
            {
                new Status { Status_ID=1,StatusName="Active",StatusDesc="For all notices that have not expired and stay active for 2 weeks." },
                new Status { Status_ID=2,StatusName="Sold",StatusDesc="For all notices on sale boards where the sale has complete." },
                new Status { Status_ID=3,StatusName="Found",StatusDesc="For all notices on lost and found boards that have been re-united with owners." },
                new Status { Status_ID=4,StatusName="Expired",StatusDesc="For all notices that have expired." },
                new Status { Status_ID=5,StatusName="Active_Extended",StatusDesc="For all notices that have are part of gold membership and stay active for 4 weeks." }
            };

            statuses.ForEach(s => context.Status.Add(s));
            context.SaveChanges();

            var boardtypes = new List<BoardType>
            {
                new BoardType { BoardType_ID=1,BoardType_Name="Sales",BoardType_Desc="Boards of this type are used for listing items fro sale" },
                new BoardType { BoardType_ID=2,BoardType_Name="Wanted",BoardType_Desc="Boards of this type are used for searching for wanted items" },
                new BoardType { BoardType_ID=3,BoardType_Name="Lost",BoardType_Desc="Boards of this type are used for listing lost items" },
                new BoardType { BoardType_ID=4,BoardType_Name="Found",BoardType_Desc="Boards of this type are used for listing found items" },
                new BoardType { BoardType_ID=5,BoardType_Name="Services",BoardType_Desc="Boards of this type are used for listing services available" },
                new BoardType { BoardType_ID=6,BoardType_Name="General",BoardType_Desc="Boards of this type are used for general listings" }
            };

            boardtypes.ForEach(bt => context.BoardTypes.Add(bt));
            context.SaveChanges();

            var perorgs = new List<PerOrg>
            {
                new PerOrg { PerOrg_ID=1,OrganisationName="NoticeBoard",FirstName="",LastName="", Email="" },
                new PerOrg { PerOrg_ID=2,OrganisationName="",FirstName="System",LastName="Administrator", Email="sysadmin@nb.com" },
                new PerOrg { PerOrg_ID=3,OrganisationName="",FirstName="Kenny",LastName="Lin", Email="kenny@lin.co.uk" },
                new PerOrg { PerOrg_ID=4,OrganisationName="",FirstName="Socorro",LastName="Abrahams", Email="socorro_abrahams@abrahams.co.uk" },
                new PerOrg { PerOrg_ID=5,OrganisationName="",FirstName="Alfreda",LastName="Delsoin", Email="adelsoin@yahoo.com" },
                new PerOrg { PerOrg_ID=6,OrganisationName="",FirstName="Deeanna",LastName="Juhas", Email="deeanna_juhas@gmail.com" },
                new PerOrg { PerOrg_ID=7,OrganisationName="",FirstName="Robt",LastName="Blanck", Email="robt.blanck@yahoo.com" },
                new PerOrg { PerOrg_ID=8,OrganisationName="",FirstName="Amos",LastName="Limberg", Email="alimberg@limberg.com.au" },
                new PerOrg { PerOrg_ID=9,OrganisationName="",FirstName="Mari",LastName="Lueckenbach", Email="mari_lueckenbach@yahoo.com" },
                new PerOrg { PerOrg_ID=10,OrganisationName="",FirstName="Jamey",LastName="Tetter", Email="jamey.tetter@gmail.com" },
                new PerOrg { PerOrg_ID=11,OrganisationName="",FirstName="Lashaun",LastName="Casteneda", Email="lashaun.casteneda@casteneda.com" },
                new PerOrg { PerOrg_ID=12,OrganisationName="",FirstName="Serita",LastName="Barthlow", Email="serita_barthlow@gmail.com" },
                new PerOrg { PerOrg_ID=13,OrganisationName="",FirstName="Kattie",LastName="Ozane", Email="kozane@gmail.com" },
                new PerOrg { PerOrg_ID=14,OrganisationName="",FirstName="Tonja",LastName="Driesenga", Email="tdriesenga@driesenga.co.uk" },
                new PerOrg { PerOrg_ID=15,OrganisationName="",FirstName="Alaine",LastName="Bergesen", Email="alaine_bergesen@cox.net" },
                new PerOrg { PerOrg_ID=16,OrganisationName="",FirstName="Verona",LastName="Jobst", Email="verona_jobst@jobst.org" },
                new PerOrg { PerOrg_ID=17,OrganisationName="",FirstName="Tawna",LastName="Buvens", Email="tawna@gmail.com" },
                new PerOrg { PerOrg_ID=18,OrganisationName="",FirstName="Donte",LastName="Kines", Email="dkines@hotmail.com" },
                new PerOrg { PerOrg_ID=19,OrganisationName="",FirstName="Marsha",LastName="Farnham", Email="marsha@farnham.com.au" },
                new PerOrg { PerOrg_ID=20,OrganisationName="",FirstName="Bette",LastName="Digiovanni", Email="bette.digiovanni@digiovanni.org" },
                new PerOrg { PerOrg_ID=21,OrganisationName="",FirstName="Deonna",LastName="Kippley", Email="deonna_kippley@hotmail.com" },
                new PerOrg { PerOrg_ID=22,OrganisationName="",FirstName="Theron",LastName="Merriam", Email="theron@merriam.co.uk" },
                new PerOrg { PerOrg_ID=23,OrganisationName="",FirstName="Louis",LastName="Brueck", Email="louis.brueck@brueck.net.au" },
                new PerOrg { PerOrg_ID=24,OrganisationName="",FirstName="Carin",LastName="Deleo", Email="cdeleo@deleo.com" },
                new PerOrg { PerOrg_ID=25,OrganisationName="",FirstName="Darrin",LastName="Mathiasen", Email="dmathiasen@hotmail.com" },
                new PerOrg { PerOrg_ID=26,OrganisationName="",FirstName="Kayleigh",LastName="Lace", Email="kayleigh.lace@yahoo.com" },
                new PerOrg { PerOrg_ID=27,OrganisationName="",FirstName="Talia",LastName="Riopelle", Email="talia_riopelle@aol.com" },
                new PerOrg { PerOrg_ID=28,OrganisationName="",FirstName="Sommer",LastName="Agar", Email="sagar@agar.net.au" },
                new PerOrg { PerOrg_ID=29,OrganisationName="",FirstName="Barb",LastName="Latina", Email="blatina@hotmail.com" },
                new PerOrg { PerOrg_ID=30,OrganisationName="",FirstName="Tricia",LastName="Peressini", Email="tperessini@yahoo.com" },
                new PerOrg { PerOrg_ID=31,OrganisationName="",FirstName="Pearlene",LastName="Boudrie", Email="pboudrie@boudrie.net.au" },
                new PerOrg { PerOrg_ID=32,OrganisationName="",FirstName="Dortha",LastName="Yaccarino", Email="dortha@hotmail.com" },
                new PerOrg { PerOrg_ID=33,OrganisationName="",FirstName="Lamar",LastName="Suite", Email="lsuite@yahoo.com" },
                new PerOrg { PerOrg_ID=34,OrganisationName="",FirstName="Desiree",LastName="Englund", Email="denglund@gmail.com" },
                new PerOrg { PerOrg_ID=35,OrganisationName="",FirstName="Iesha",LastName="Wardle", Email="iesha@gmail.com" },
                new PerOrg { PerOrg_ID=36,OrganisationName="",FirstName="Barney",LastName="Dewer", Email="bdewer@gmail.com" },
                new PerOrg { PerOrg_ID=37,OrganisationName="",FirstName="Rosalind",LastName="Persechino", Email="rosalind.persechino@aol.com" },
                new PerOrg { PerOrg_ID=38,OrganisationName="",FirstName="Merri",LastName="Geberth", Email="merri.geberth@geberth.com" },
                new PerOrg { PerOrg_ID=39,OrganisationName="",FirstName="Billy",LastName="Venus", Email="billy.venus@yahoo.com" },
                new PerOrg { PerOrg_ID=40,OrganisationName="",FirstName="Linwood",LastName="Wessner", Email="linwood.wessner@hotmail.com" },
                new PerOrg { PerOrg_ID=41,OrganisationName="",FirstName="Pilar",LastName="Seelig", Email="pilar@yahoo.com" },
                new PerOrg { PerOrg_ID=42,OrganisationName="",FirstName="Lilli",LastName="Cureau", Email="lilli@yahoo.com" },
                new PerOrg { PerOrg_ID=43,OrganisationName="",FirstName="Lachelle",LastName="Andrzejewski", Email="lachelle.andrzejewski@andrzejewski.com.au" },
                new PerOrg { PerOrg_ID=44,OrganisationName="",FirstName="Kathryn",LastName="Bonalumi", Email="kathryn.bonalumi@yahoo.com" },
                new PerOrg { PerOrg_ID=45,OrganisationName="",FirstName="India",LastName="Sifford", Email="isifford@sifford.org" },
                new PerOrg { PerOrg_ID=46,OrganisationName="",FirstName="Vicente",LastName="Rawicki", Email="vicente_rawicki@hotmail.com" },
                new PerOrg { PerOrg_ID=47,OrganisationName="",FirstName="Noah",LastName="Kalafatis", Email="noah.kalafatis@aol.com" },
                new PerOrg { PerOrg_ID=48,OrganisationName="",FirstName="Eleonora",LastName="Ventry", Email="eleonora@gmail.com" },
                new PerOrg { PerOrg_ID=49,OrganisationName="",FirstName="Raymon",LastName="Calvaresi", Email="raymon.calvaresi@gmail.com" },
                new PerOrg { PerOrg_ID=50,OrganisationName="",FirstName="Margret",LastName="Alcazar", Email="margret@alcazar.co.uk" },
                new PerOrg { PerOrg_ID=51,OrganisationName="",FirstName="Izetta",LastName="Dewar", Email="idewar@dewar.com" },
                new PerOrg { PerOrg_ID=52,OrganisationName="",FirstName="Tula",LastName="Nahmias", Email="tnahmias@nahmias.co.uk" },
                new PerOrg { PerOrg_ID=53,OrganisationName="",FirstName="Carman",LastName="Robasciotti", Email="carman_robasciotti@hotmail.com" },
                new PerOrg { PerOrg_ID=54,OrganisationName="",FirstName="Truman",LastName="Mondale", Email="truman.mondale@aol.com" },
                new PerOrg { PerOrg_ID=55,OrganisationName="",FirstName="Fletcher",LastName="Flosi", Email="fletcher.flosi@yahoo.com" },
                new PerOrg { PerOrg_ID=56,OrganisationName="",FirstName="Jamal",LastName="Vanausdal", Email="jamal@vanausdal.org" },
                new PerOrg { PerOrg_ID=57,OrganisationName="",FirstName="Dorcas",LastName="Diebold", Email="dorcas_diebold@diebold.com" },
                new PerOrg { PerOrg_ID=58,OrganisationName="",FirstName="Olga",LastName="Adessa", Email="oadessa@cox.net" },
                new PerOrg { PerOrg_ID=59,OrganisationName="",FirstName="Marion",LastName="Letran", Email="marion_letran@cox.net" },
                new PerOrg { PerOrg_ID=60,OrganisationName="",FirstName="Freeman",LastName="Rudig", Email="freeman@yahoo.com" },
                new PerOrg { PerOrg_ID=61,OrganisationName="",FirstName="Curtis",LastName="Ware", Email="curtis@ware.net.au" },
                new PerOrg { PerOrg_ID=62,OrganisationName="",FirstName="Alison",LastName="Mahlum", Email="alison_mahlum@hotmail.com" },
                new PerOrg { PerOrg_ID=63,OrganisationName="",FirstName="Kristin",LastName="Shiflet", Email="kristin@hotmail.com" },
                new PerOrg { PerOrg_ID=64,OrganisationName="",FirstName="Jarod",LastName="Catalina", Email="jcatalina@aol.com" },
                new PerOrg { PerOrg_ID=65,OrganisationName="",FirstName="Tegan",LastName="Arceo", Email="tegan.arceo@arceo.org" },
                new PerOrg { PerOrg_ID=66,OrganisationName="",FirstName="Alexis",LastName="Morguson", Email="amorguson@morguson.com.au" },
                new PerOrg { PerOrg_ID=67,OrganisationName="",FirstName="Torie",LastName="Deras", Email="torie_deras@yahoo.com" },
                new PerOrg { PerOrg_ID=68,OrganisationName="",FirstName="Celestine",LastName="Pritt", Email="celestine_pritt@cox.net" },
                new PerOrg { PerOrg_ID=69,OrganisationName="",FirstName="Chantay",LastName="Jirsa", Email="chantay_jirsa@jirsa.co.uk" },
                new PerOrg { PerOrg_ID=70,OrganisationName="",FirstName="Selene",LastName="Zeng", Email="selene@yahoo.com" },
                new PerOrg { PerOrg_ID=71,OrganisationName="",FirstName="Lynelle",LastName="Koury", Email="lynelle.koury@koury.net.au" },
                new PerOrg { PerOrg_ID=72,OrganisationName="",FirstName="Carli",LastName="Bame", Email="carli@yahoo.com" },
                new PerOrg { PerOrg_ID=73,OrganisationName="",FirstName="Delmy",LastName="Ahle", Email="delmy.ahle@hotmail.com" },
                new PerOrg { PerOrg_ID=74,OrganisationName="",FirstName="Lynna",LastName="Breheny", Email="lynna@yahoo.com" }
            };

            perorgs.ForEach(po => context.PerOrgs.Add(po));
            context.SaveChanges();

            var locations = new List<Location>
            {
                new Location { Location_ID=1,Address="49 Scotia Street",Suburb="Wakatu",City="Nelson",State="Tasman",Postcode="7011",Country="New Zealand" },
                new Location { Location_ID=2,Address="5 Middletown Blvd",Suburb="",City="Richmond",State="BC",Postcode="V6Y 1L9",Country="Canada" },
                new Location { Location_ID=3,Address="1 Towson St",Suburb="",City="Howe of Fife and Tay Coast War",State="Fife",Postcode="KY14 6AH",Country="United Kingdom" },
                new Location { Location_ID=4,Address="93 Clyde Rd #9",Suburb="",City="Deepdale Ward",State="Lancashire",Postcode="PR1 6TN",Country="United Kingdom" },
                new Location { Location_ID=5,Address="4373 Washington St",Suburb="",City="Bongeen",State="QL",Postcode="4356",Country="Australia" },
                new Location { Location_ID=6,Address="14302 Pennsylvania Ave",Suburb="",City="Huntingdon Valley",State="PA",Postcode="19006",Country="United States of America" },
                new Location { Location_ID=7,Address="790 E Wisconsin Ave",Suburb="",City="Woodbury",State="TA",Postcode="7120",Country="Australia" },
                new Location { Location_ID=8,Address="8 2nd St",Suburb="",City="Don",State="TA",Postcode="7310",Country="Australia" },
                new Location { Location_ID=9,Address="1 Century Park E",Suburb="",City="San Diego",State="CA",Postcode="92110",Country="United States of America" },
                new Location { Location_ID=10,Address="28 Standiford Ave #6",Suburb="",City="Bundaberg West",State="QL",Postcode="4670",Country="Australia" },
                new Location { Location_ID=11,Address="894 Feather River Blvd",Suburb="",City="Edmonton",State="AB",Postcode="T6L 4W9",Country="Canada" },
                new Location { Location_ID=12,Address="190 34th St #8",Suburb="",City="Nangetty",State="WA",Postcode="6522",Country="Australia" },
                new Location { Location_ID=13,Address="526 Liffey St #759",Suburb="",City="Westbury",State="Wiltshire",Postcode="BA13 3QU",Country="United Kingdom" },
                new Location { Location_ID=14,Address="8 South John St",Suburb="",City="Lamport",State="Northamptonshire",Postcode="NN6 9XW",Country="United Kingdom" },
                new Location { Location_ID=15,Address="7667 S Hulen St #42",Suburb="",City="Yonkers",State="NY",Postcode="10701",Country="United States of America" },
                new Location { Location_ID=16,Address="9041 Grand Plaza Plac",Suburb="",City="Montreal",State="QC",Postcode="H3V 1E3",Country="Canada" },
                new Location { Location_ID=17,Address="3305 Nabell Ave #679",Suburb="",City="New York",State="NY",Postcode="10009",Country="United States of America" },
                new Location { Location_ID=18,Address="3 Aspen St",Suburb="",City="Worcester",State="MA",Postcode="01602",Country="United States of America" },
                new Location { Location_ID=19,Address="577 Cleveland Ave",Suburb="",City="Glenmore Park",State="NS",Postcode="2745",Country="Australia" },
                new Location { Location_ID=20,Address="345 Broadway St",Suburb="",City="London",State="ON",Postcode="N6K 4J9",Country="Canada" },
                new Location { Location_ID=21,Address="57 Haven Ave #90",Suburb="",City="Southfield",State="MI",Postcode="48075",Country="United States of America" },
                new Location { Location_ID=22,Address="869 Luke St",Suburb="",City="Wonersh",State="Surrey",Postcode="GU5 0QU",Country="United Kingdom" },
                new Location { Location_ID=23,Address="73 12th St",Suburb="",City="Larrakeyah",State="NT",Postcode="820",Country="Australia" },
                new Location { Location_ID=24,Address="1844 Southern Blvd",Suburb="",City="Little Rock",State="AR",Postcode="72202",Country="United States of America" },
                new Location { Location_ID=25,Address="35 Peconic Ave #4",Suburb="",City="Boucherville",State="QC",Postcode="J4B 3Y4",Country="Canada" },
                new Location { Location_ID=26,Address="43 Huey P Long Ave",Suburb="",City="Lafayette",State="LA",Postcode="70508",Country="United States of America" },
                new Location { Location_ID=27,Address="1 N Harlem Ave #9",Suburb="",City="Orange",State="NJ",Postcode="07050",Country="United States of America" },
                new Location { Location_ID=28,Address="3 N Ridge Ave",Suburb="",City="Kadina",State="SA",Postcode="5554",Country="Australia" },
                new Location { Location_ID=29,Address="1 National Plac #6619",Suburb="",City="Larrakeyah",State="NT",Postcode="820",Country="Australia" },
                new Location { Location_ID=30,Address="3 Industrial Blvd",Suburb="",City="Pintharuka",State="WA",Postcode="6623",Country="Australia" },
                new Location { Location_ID=31,Address="8978 W Henrietta Rd",Suburb="",City="Minden",State="QL",Postcode="4311",Country="Australia" },
                new Location { Location_ID=32,Address="6 Chestnut St",Suburb="",City="Gwersyllt Community",State="Wrexham",Postcode="LL11 4RJ",Country="United Kingdom" },
                new Location { Location_ID=33,Address="6301 Dorset Rd",Suburb="",City="Harefield Ward",State="Greater London",Postcode="UB9 6LF",Country="United Kingdom" },
                new Location { Location_ID=34,Address="9495 Central Hwy #66",Suburb="",City="East Bowes",State="WA",Postcode="6535",Country="Australia" },
                new Location { Location_ID=35,Address="781 Alabama Ave",Suburb="",City="Etobicoke",State="ON",Postcode="M8Z 2C1",Country="Canada" },
                new Location { Location_ID=36,Address="88 Norris Ave #2",Suburb="",City="Bedford",State="NS",Postcode="B4A 3V5",Country="Canada" },
                new Location { Location_ID=37,Address="86 Shady Run Rd",Suburb="",City="Kanata",State="ON",Postcode="K2M 1E6",Country="Canada" },
                new Location { Location_ID=38,Address="4 Beaverbrook Rd",Suburb="",City="Winnipeg",State="MB",Postcode="R2P 2J7",Country="Canada" },
                new Location { Location_ID=39,Address="61 Miriam St",Suburb="",City="Abbey Road Ward",State="Greater London",Postcode="NW8 9BD",Country="United Kingdom" },
                new Location { Location_ID=40,Address="9634 South St",Suburb="",City="Saltwater River",State="TA",Postcode="7186",Country="Australia" },
                new Location { Location_ID=41,Address="4 Ogwen St",Suburb="",City="Chichester",State="West Sussex",Postcode="PO19 9PF",Country="United Kingdom" },
                new Location { Location_ID=42,Address="42 Hey Green Rd",Suburb="",City="Deepdale Ward",State="Lancashire",Postcode="PR1 6TL",Country="United Kingdom" },
                new Location { Location_ID=43,Address="262 Montauk Blvd",Suburb="",City="Cherrybrook",State="NS",Postcode="2126",Country="Australia" },
                new Location { Location_ID=44,Address="86 Worth St #272",Suburb="",City="Tibradden",State="WA",Postcode="6532",Country="Australia" },
                new Location { Location_ID=45,Address="162 Sunrise Plz",Suburb="",City="Toronto",State="ON",Postcode="M5N 1J1",Country="Canada" },
                new Location { Location_ID=46,Address="3060 St Ambrose Grove #261",Suburb="",City="Aldridge Central and South War",State="West Midlands",Postcode="WS9 8UR",Country="United Kingdom" },
                new Location { Location_ID=47,Address="1950 5th Ave",Suburb="",City="Milwaukee",State="WI",Postcode="53209",Country="United States of America" },
                new Location { Location_ID=48,Address="758 Woodhouse St",Suburb="",City="Soho Ward",State="West Midlands",Postcode="B21 0UE",Country="United Kingdom" },
                new Location { Location_ID=49,Address="6538 E Pomona St #60",Suburb="",City="Indianapolis",State="IN",Postcode="46222",Country="United States of America" },
                new Location { Location_ID=50,Address="5466 Sedley St",Suburb="",City="Coatbridge South Ward",State="North Lanarkshire",Postcode="ML5 4LJ",Country="United Kingdom" },
                new Location { Location_ID=51,Address="2 W Scyene Rd #3",Suburb="",City="Baltimore",State="MD",Postcode="21217",Country="United States of America" },
                new Location { Location_ID=52,Address="64 Croyland St",Suburb="",City="Clackmannanshire South Ward",State="Clackmannanshire",Postcode="FK10 2LA",Country="United Kingdom" },
                new Location { Location_ID=53,Address="4 Spinning Wheel Ln",Suburb="",City="Granya",State="VI",Postcode="3701",Country="Australia" },
                new Location { Location_ID=54,Address="1657 N Green St",Suburb="",City="Peterborough",State="ON",Postcode="K9J 0A1",Country="Canada" },
                new Location { Location_ID=55,Address="394 Manchester Blvd",Suburb="",City="Rockford",State="IL",Postcode="61109",Country="United States of America" },
                new Location { Location_ID=56,Address="53075 Sw 152nd Ter #615",Suburb="",City="Monroe Township",State="NJ",Postcode="08831",Country="United States of America" },
                new Location { Location_ID=57,Address="8899 E Slauson Ave",Suburb="",City="Mississauga",State="ON",Postcode="L5M 4A7",Country="Canada" },
                new Location { Location_ID=58,Address="8507 Upland St",Suburb="",City="Burlington",State="ON",Postcode="L7P 4T1",Country="Canada" },
                new Location { Location_ID=59,Address="5670 Leonis Blvd",Suburb="",City="Gatineau",State="QC",Postcode="J8Y 5Z4",Country="Canada" },
                new Location { Location_ID=60,Address="4 W Sedgley Ave",Suburb="",City="Otterburn Park",State="QC",Postcode="J3H 4V8",Country="Canada" },
                new Location { Location_ID=61,Address="51 Greenwood Ave",Suburb="",City="Ridgewood",State="WA",Postcode="6030",Country="Australia" },
                new Location { Location_ID=62,Address="841 N Monroe St",Suburb="",City="Belleville",State="ON",Postcode="K8N 2W3",Country="Canada" },
                new Location { Location_ID=63,Address="503 Fulford Ave",Suburb="",City="Somers",State="VI",Postcode="3927",Country="Australia" },
                new Location { Location_ID=64,Address="60 Sunrise Ave",Suburb="",City="North Bay",State="ON",Postcode="P1B 2L4",Country="Canada" },
                new Location { Location_ID=65,Address="62260 Park Stre",Suburb="",City="Monroe Township",State="NJ",Postcode="08831",Country="United States of America" },
                new Location { Location_ID=66,Address="9 Old York Rd #418",Suburb="",City="Weetulta",State="SA",Postcode="5573",Country="Australia" },
                new Location { Location_ID=67,Address="700 Factory Ave #5649",Suburb="",City="Yeppoon",State="QL",Postcode="4703",Country="Australia" },
                new Location { Location_ID=68,Address="79 E 92nd St",Suburb="",City="Ottawa",State="ON",Postcode="K1G 3B6",Country="Canada" },
                new Location { Location_ID=69,Address="966 Bower St",Suburb="",City="Frimley Green Ward",State="Surrey",Postcode="GU16 9BB",Country="United Kingdom" },
                new Location { Location_ID=70,Address="2 Prince Rupert St",Suburb="",City="West Wickham Ward",State="Greater London",Postcode="BR3 6SX",Country="United Kingdom" },
                new Location { Location_ID=71,Address="7696 Carey Ave",Suburb="",City="Digby",State="VI",Postcode="3309",Country="Australia" },
                new Location { Location_ID=72,Address="6584 S Bascom Ave #371",Suburb="",City="Elanora",State="QL",Postcode="4221",Country="Australia" },
                new Location { Location_ID=73,Address="65895 S 16th St",Suburb="",City="Providence",State="RI",Postcode="02909",Country="United States of America" },
                new Location { Location_ID=74,Address="1 James St #4",Suburb="",City="St. Andrews Ward",State="Fife",Postcode="KY16 9EE",Country="United Kingdom" }
            };

            locations.ForEach(l => context.Locations.Add(l));
            context.SaveChanges();

            var perorgLocations = new List<PerOrgLocation>
            {
                new PerOrgLocation { PerOrg_ID=1,Location_ID=1,PrefContactNumber="022-677-1268",AltContactNumber="022-608-8781"},
                new PerOrgLocation { PerOrg_ID=2,Location_ID=1,PrefContactNumber="022-677-1268",AltContactNumber="022-608-8781"},
                new PerOrgLocation { PerOrg_ID=3,Location_ID=3,PrefContactNumber="01753-900033",AltContactNumber="01473-417906"},
                new PerOrgLocation { PerOrg_ID=4,Location_ID=4,PrefContactNumber="01311-567052",AltContactNumber="01387-779081"},
                new PerOrgLocation { PerOrg_ID=5,Location_ID=5,PrefContactNumber="07-7369-8849",AltContactNumber="0419-246-570"},
                new PerOrgLocation { PerOrg_ID=6,Location_ID=6,PrefContactNumber="215-211-9589",AltContactNumber="215-417-9563"},
                new PerOrgLocation { PerOrg_ID=7,Location_ID=7,PrefContactNumber="03-6517-9318",AltContactNumber="0415-690-961"},
                new PerOrgLocation { PerOrg_ID=8,Location_ID=8,PrefContactNumber="03-4539-9131",AltContactNumber="0492-444-651"},
                new PerOrgLocation { PerOrg_ID=9,Location_ID=9,PrefContactNumber="858-793-9684",AltContactNumber="858-228-5683"},
                new PerOrgLocation { PerOrg_ID=10,Location_ID=10,PrefContactNumber="07-6073-5039",AltContactNumber="0481-690-589"},
                new PerOrgLocation { PerOrg_ID=11,Location_ID=11,PrefContactNumber="780-751-5370",AltContactNumber="780-433-1426"},
                new PerOrgLocation { PerOrg_ID=12,Location_ID=12,PrefContactNumber="08-2941-7378",AltContactNumber="0493-703-129"},
                new PerOrgLocation { PerOrg_ID=13,Location_ID=13,PrefContactNumber="01322-491007",AltContactNumber="01807-524286"},
                new PerOrgLocation { PerOrg_ID=14,Location_ID=14,PrefContactNumber="01683-204727",AltContactNumber="01384-883931"},
                new PerOrgLocation { PerOrg_ID=15,Location_ID=15,PrefContactNumber="914-300-9193",AltContactNumber="914-654-1426"},
                new PerOrgLocation { PerOrg_ID=16,Location_ID=16,PrefContactNumber="514-842-7487",AltContactNumber="514-879-3678"},
                new PerOrgLocation { PerOrg_ID=17,Location_ID=17,PrefContactNumber="212-674-9610",AltContactNumber="212-462-9157"},
                new PerOrgLocation { PerOrg_ID=18,Location_ID=18,PrefContactNumber="508-429-8576",AltContactNumber="508-843-1426"},
                new PerOrgLocation { PerOrg_ID=19,Location_ID=19,PrefContactNumber="02-5402-8024",AltContactNumber="0470-386-894"},
                new PerOrgLocation { PerOrg_ID=20,Location_ID=20,PrefContactNumber="519-882-6434",AltContactNumber="519-206-1305"},
                new PerOrgLocation { PerOrg_ID=21,Location_ID=21,PrefContactNumber="248-913-4677",AltContactNumber="248-793-4966"},
                new PerOrgLocation { PerOrg_ID=22,Location_ID=22,PrefContactNumber="01655-809574",AltContactNumber="01859-311417"},
                new PerOrgLocation { PerOrg_ID=23,Location_ID=23,PrefContactNumber="08-5228-3628",AltContactNumber="0471-229-188"},
                new PerOrgLocation { PerOrg_ID=24,Location_ID=24,PrefContactNumber="501-308-1040",AltContactNumber="501-409-6072"},
                new PerOrgLocation { PerOrg_ID=25,Location_ID=25,PrefContactNumber="450-536-7426",AltContactNumber="450-609-7284"},
                new PerOrgLocation { PerOrg_ID=26,Location_ID=26,PrefContactNumber="337-740-9323",AltContactNumber="337-751-2326"},
                new PerOrgLocation { PerOrg_ID=27,Location_ID=27,PrefContactNumber="973-245-2133",AltContactNumber="973-818-9788"},
                new PerOrgLocation { PerOrg_ID=28,Location_ID=28,PrefContactNumber="08-9130-3372",AltContactNumber="0486-599-199"},
                new PerOrgLocation { PerOrg_ID=29,Location_ID=29,PrefContactNumber="08-8506-7259",AltContactNumber="0443-657-148"},
                new PerOrgLocation { PerOrg_ID=30,Location_ID=30,PrefContactNumber="08-4326-1560",AltContactNumber="0484-192-990"},
                new PerOrgLocation { PerOrg_ID=31,Location_ID=31,PrefContactNumber="07-4463-7223",AltContactNumber="0462-627-260"},
                new PerOrgLocation { PerOrg_ID=32,Location_ID=32,PrefContactNumber="01528-240870",AltContactNumber="01254-458143"},
                new PerOrgLocation { PerOrg_ID=33,Location_ID=33,PrefContactNumber="01716-613102",AltContactNumber="01885-144424"},
                new PerOrgLocation { PerOrg_ID=34,Location_ID=34,PrefContactNumber="08-5289-4594",AltContactNumber="0414-731-630"},
                new PerOrgLocation { PerOrg_ID=35,Location_ID=35,PrefContactNumber="416-989-2001",AltContactNumber="416-615-4957"},
                new PerOrgLocation { PerOrg_ID=36,Location_ID=36,PrefContactNumber="902-287-1148",AltContactNumber="902-440-9745"},
                new PerOrgLocation { PerOrg_ID=37,Location_ID=37,PrefContactNumber="613-975-5760",AltContactNumber="613-310-5882"},
                new PerOrgLocation { PerOrg_ID=38,Location_ID=38,PrefContactNumber="204-894-9221",AltContactNumber="204-710-5400"},
                new PerOrgLocation { PerOrg_ID=39,Location_ID=39,PrefContactNumber="01537-356648",AltContactNumber="01703-435212"},
                new PerOrgLocation { PerOrg_ID=40,Location_ID=40,PrefContactNumber="03-6053-2447",AltContactNumber="0487-913-509"},
                new PerOrgLocation { PerOrg_ID=41,Location_ID=41,PrefContactNumber="01356-866584",AltContactNumber="01814-760513"},
                new PerOrgLocation { PerOrg_ID=42,Location_ID=42,PrefContactNumber="01752-399931",AltContactNumber="01363-139614"},
                new PerOrgLocation { PerOrg_ID=43,Location_ID=43,PrefContactNumber="02-3416-9617",AltContactNumber="0453-493-910"},
                new PerOrgLocation { PerOrg_ID=44,Location_ID=44,PrefContactNumber="08-3071-2258",AltContactNumber="0455-699-311"},
                new PerOrgLocation { PerOrg_ID=45,Location_ID=45,PrefContactNumber="416-866-6707",AltContactNumber="416-539-4631"},
                new PerOrgLocation { PerOrg_ID=46,Location_ID=46,PrefContactNumber="01327-770774",AltContactNumber="01286-258121"},
                new PerOrgLocation { PerOrg_ID=47,Location_ID=47,PrefContactNumber="414-263-5287",AltContactNumber="414-660-9766"},
                new PerOrgLocation { PerOrg_ID=48,Location_ID=48,PrefContactNumber="01966-685595",AltContactNumber="01762-396161"},
                new PerOrgLocation { PerOrg_ID=49,Location_ID=49,PrefContactNumber="317-825-4724",AltContactNumber="317-342-1532"},
                new PerOrgLocation { PerOrg_ID=50,Location_ID=50,PrefContactNumber="01626-590776",AltContactNumber="01633-731246"},
                new PerOrgLocation { PerOrg_ID=51,Location_ID=51,PrefContactNumber="410-473-1708",AltContactNumber="410-522-7621"},
                new PerOrgLocation { PerOrg_ID=52,Location_ID=52,PrefContactNumber="01846-815511",AltContactNumber="01320-223056"},
                new PerOrgLocation { PerOrg_ID=53,Location_ID=53,PrefContactNumber="03-1570-9956",AltContactNumber="0420-704-683"},
                new PerOrgLocation { PerOrg_ID=54,Location_ID=54,PrefContactNumber="705-757-7389",AltContactNumber="705-234-5820"},
                new PerOrgLocation { PerOrg_ID=55,Location_ID=55,PrefContactNumber="815-828-2147",AltContactNumber="815-426-5657"},
                new PerOrgLocation { PerOrg_ID=56,Location_ID=56,PrefContactNumber="732-234-1546",AltContactNumber="732-904-2931"},
                new PerOrgLocation { PerOrg_ID=57,Location_ID=57,PrefContactNumber="905-860-8703",AltContactNumber="905-269-7682"},
                new PerOrgLocation { PerOrg_ID=58,Location_ID=58,PrefContactNumber="905-775-6413",AltContactNumber="905-340-9290"},
                new PerOrgLocation { PerOrg_ID=59,Location_ID=59,PrefContactNumber="819-966-7240",AltContactNumber="819-730-7626"},
                new PerOrgLocation { PerOrg_ID=60,Location_ID=60,PrefContactNumber="450-347-6388",AltContactNumber="450-586-7429"},
                new PerOrgLocation { PerOrg_ID=61,Location_ID=61,PrefContactNumber="08-6278-9532",AltContactNumber="0484-331-585"},
                new PerOrgLocation { PerOrg_ID=62,Location_ID=62,PrefContactNumber="613-862-3122",AltContactNumber="613-259-2601"},
                new PerOrgLocation { PerOrg_ID=63,Location_ID=63,PrefContactNumber="03-4529-7210",AltContactNumber="0488-223-788"},
                new PerOrgLocation { PerOrg_ID=64,Location_ID=64,PrefContactNumber="705-369-2146",AltContactNumber="705-915-3282"},
                new PerOrgLocation { PerOrg_ID=65,Location_ID=65,PrefContactNumber="732-730-2692",AltContactNumber="732-705-6719"},
                new PerOrgLocation { PerOrg_ID=66,Location_ID=66,PrefContactNumber="08-1895-1457",AltContactNumber="0475-760-952"},
                new PerOrgLocation { PerOrg_ID=67,Location_ID=67,PrefContactNumber="07-8371-4719",AltContactNumber="0426-991-115"},
                new PerOrgLocation { PerOrg_ID=68,Location_ID=68,PrefContactNumber="613-875-3120",AltContactNumber="613-291-6460"},
                new PerOrgLocation { PerOrg_ID=69,Location_ID=69,PrefContactNumber="01721-910475",AltContactNumber="01324-899303"},
                new PerOrgLocation { PerOrg_ID=70,Location_ID=70,PrefContactNumber="01741-833047",AltContactNumber="01345-685146"},
                new PerOrgLocation { PerOrg_ID=71,Location_ID=71,PrefContactNumber="03-5213-8219",AltContactNumber="0462-987-152"},
                new PerOrgLocation { PerOrg_ID=72,Location_ID=72,PrefContactNumber="07-5354-7251",AltContactNumber="0499-207-236"},
                new PerOrgLocation { PerOrg_ID=73,Location_ID=73,PrefContactNumber="401-458-2547",AltContactNumber="401-559-8961"},
                new PerOrgLocation { PerOrg_ID=74,Location_ID=74,PrefContactNumber="01914-909214",AltContactNumber="01868-440687"}
            };

            perorgLocations.ForEach(pol => context.PerOrgLocations.Add(pol));
            context.SaveChanges();

            var membersof = new List<MemberOf>
            {
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=2  },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=3  },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=4  },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=5  },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=6  },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=7  },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=8  },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=9  },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=10 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=11 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=12 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=13 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=14 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=15 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=16 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=17 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=18 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=19 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=20 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=21 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=22 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=23 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=24 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=25 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=26 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=27 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=28 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=29 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=30 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=31 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=32 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=33 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=34 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=35 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=36 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=37 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=38 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=39 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=40 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=41 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=42 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=43 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=44 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=45 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=46 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=47 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=48 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=49 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=50 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=51 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=52 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=53 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=54 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=55 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=56 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=57 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=58 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=59 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=60 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=61 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=62 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=63 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=64 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=65 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=66 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=67 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=68 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=69 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=70 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=71 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=72 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=73 },
                new MemberOf { PerOrgParent_ID=1,PerOrgChild_ID=74 }
            };

            membersof.ForEach(mo => context.MemberOfs.Add(mo));
            context.SaveChanges();

            var memberofroles = new List<MemberOfRole>
            {
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=2 ,Role_ID=3 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=3 ,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=4 ,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=5 ,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=6 ,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=7 ,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=8 ,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=9 ,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=10,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=11,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=12,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=13,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=14,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=15,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=16,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=17,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=18,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=19,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=20,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=21,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=22,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=23,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=24,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=25,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=26,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=27,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=28,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=29,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=30,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=31,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=32,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=33,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=34,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=35,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=36,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=37,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=38,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=39,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=40,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=41,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=42,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=43,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=44,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=45,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=46,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=47,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=48,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=49,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=50,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=51,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=52,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=53,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=54,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=55,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=56,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=57,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=58,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=59,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=60,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=61,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=62,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=63,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=64,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=65,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=66,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=67,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=68,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=69,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=70,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=71,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=72,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=73,Role_ID=1 },
                new MemberOfRole { PerOrgParent_ID=1,PerOrgChild_ID=74,Role_ID=1 }
            };

            memberofroles.ForEach(mor => context.MemerberOfRoles.Add(mor));
            context.SaveChanges();

            var boards = new List<Board>
            {
                new Board { Board_ID=1,BoardType_ID=1,PerOrg_ID=1,BoardName="For Sale",BoardDesc="Have something you want to sell, list it here." },
                new Board { Board_ID=2,BoardType_ID=2,PerOrg_ID=1,BoardName="Wanted",BoardDesc="Are you looking for something, perhaps you need a new bike or car, look no further." },
                new Board { Board_ID=3,BoardType_ID=3,PerOrg_ID=1,BoardName="Lost Items",BoardDesc="Have you found something that might be important to someone, list it here for best results." }
            };

            boards.ForEach(b => context.Boards.Add(b));
            context.SaveChanges();

            var viewableboards = new List<ViewableBoard>
            {
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=2 ,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=3 ,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=4 ,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=5 ,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=6 ,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=7 ,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=8 ,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=9 ,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=10,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=11,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=12,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=13,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=14,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=15,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=16,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=17,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=18,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=19,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=20,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=21,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=22,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=23,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=24,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=25,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=26,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=27,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=28,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=29,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=30,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=31,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=32,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=33,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=34,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=35,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=36,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=37,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=38,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=39,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=40,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=41,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=42,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=43,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=44,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=45,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=46,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=47,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=48,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=49,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=50,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=51,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=52,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=53,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=54,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=55,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=56,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=57,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=58,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=59,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=60,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=61,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=62,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=63,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=64,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=65,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=66,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=67,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=68,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=69,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=70,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=71,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=72,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=73,Role_ID=1 },
                new ViewableBoard { Board_ID=1,PerOrgParent_ID=1,PerOrgChild_ID=74,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=2 ,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=3 ,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=4 ,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=5 ,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=6 ,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=7 ,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=8 ,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=9 ,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=10,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=11,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=12,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=13,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=14,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=15,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=16,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=17,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=18,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=19,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=20,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=21,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=22,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=23,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=24,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=25,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=26,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=27,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=28,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=29,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=30,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=31,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=32,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=33,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=34,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=35,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=36,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=37,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=38,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=39,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=40,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=41,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=42,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=43,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=44,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=45,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=46,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=47,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=48,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=49,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=50,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=51,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=52,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=53,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=54,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=55,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=56,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=57,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=58,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=59,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=60,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=61,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=62,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=63,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=64,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=65,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=66,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=67,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=68,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=69,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=70,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=71,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=72,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=73,Role_ID=1 },
                new ViewableBoard { Board_ID=2,PerOrgParent_ID=1,PerOrgChild_ID=74,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=2 ,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=3 ,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=4 ,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=5 ,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=6 ,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=7 ,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=8 ,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=9 ,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=10,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=11,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=12,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=13,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=14,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=15,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=16,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=17,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=18,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=19,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=20,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=21,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=22,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=23,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=24,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=25,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=26,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=27,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=28,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=29,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=30,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=31,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=32,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=33,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=34,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=35,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=36,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=37,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=38,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=39,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=40,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=41,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=42,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=43,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=44,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=45,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=46,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=47,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=48,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=49,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=50,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=51,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=52,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=53,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=54,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=55,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=56,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=57,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=58,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=59,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=60,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=61,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=62,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=63,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=64,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=65,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=66,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=67,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=68,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=69,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=70,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=71,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=72,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=73,Role_ID=1 },
                new ViewableBoard { Board_ID=3,PerOrgParent_ID=1,PerOrgChild_ID=74,Role_ID=1 }
            };

            viewableboards.ForEach(vb => context.ViewableBoards.Add(vb));
            context.SaveChanges();

        }
    }
}